// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: tracker.proto
// Protobuf C++ Version: 5.29.3

#include "tracker.pb.hpp"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;

inline constexpr tracker::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : coordinates_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        id_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        time_track_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        name_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        longitude_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        latitude_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        speed_{0},
        battery_{0},
        power_{false},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR tracker::tracker(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct trackerDefaultTypeInternal {
  PROTOBUF_CONSTEXPR trackerDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~trackerDefaultTypeInternal() {}
  union {
    tracker _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 trackerDefaultTypeInternal _tracker_default_instance_;

inline constexpr tracker_list::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : trackers_{},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR tracker_list::tracker_list(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct tracker_listDefaultTypeInternal {
  PROTOBUF_CONSTEXPR tracker_listDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~tracker_listDefaultTypeInternal() {}
  union {
    tracker_list _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 tracker_listDefaultTypeInternal _tracker_list_default_instance_;
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_tracker_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_tracker_2eproto = nullptr;
const ::uint32_t
    TableStruct_tracker_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::tracker, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::tracker, _impl_.speed_),
        PROTOBUF_FIELD_OFFSET(::tracker, _impl_.battery_),
        PROTOBUF_FIELD_OFFSET(::tracker, _impl_.coordinates_),
        PROTOBUF_FIELD_OFFSET(::tracker, _impl_.power_),
        PROTOBUF_FIELD_OFFSET(::tracker, _impl_.id_),
        PROTOBUF_FIELD_OFFSET(::tracker, _impl_.time_track_),
        PROTOBUF_FIELD_OFFSET(::tracker, _impl_.name_),
        PROTOBUF_FIELD_OFFSET(::tracker, _impl_.longitude_),
        PROTOBUF_FIELD_OFFSET(::tracker, _impl_.latitude_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::tracker_list, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::tracker_list, _impl_.trackers_),
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::tracker)},
        {17, -1, -1, sizeof(::tracker_list)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::_tracker_default_instance_._instance,
    &::_tracker_list_default_instance_._instance,
};
const char descriptor_table_protodef_tracker_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\rtracker.proto\"\240\001\n\007tracker\022\r\n\005speed\030\001 \001"
    "(\005\022\017\n\007battery\030\002 \001(\005\022\023\n\013coordinates\030\003 \001(\t"
    "\022\r\n\005power\030\005 \001(\010\022\n\n\002id\030\006 \001(\t\022\022\n\ntime_trac"
    "k\030\007 \001(\t\022\014\n\004name\030\010 \001(\t\022\021\n\tlongitude\030\t \001(\t"
    "\022\020\n\010latitude\030\n \001(\t\"*\n\014tracker_list\022\032\n\010tr"
    "ackers\030\001 \003(\0132\010.trackerb\006proto3"
};
static ::absl::once_flag descriptor_table_tracker_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_tracker_2eproto = {
    false,
    false,
    230,
    descriptor_table_protodef_tracker_2eproto,
    "tracker.proto",
    &descriptor_table_tracker_2eproto_once,
    nullptr,
    0,
    2,
    schemas,
    file_default_instances,
    TableStruct_tracker_2eproto::offsets,
    file_level_enum_descriptors_tracker_2eproto,
    file_level_service_descriptors_tracker_2eproto,
};
// ===================================================================

class tracker::_Internal {
 public:
};

tracker::tracker(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:tracker)
}
inline PROTOBUF_NDEBUG_INLINE tracker::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::tracker& from_msg)
      : coordinates_(arena, from.coordinates_),
        id_(arena, from.id_),
        time_track_(arena, from.time_track_),
        name_(arena, from.name_),
        longitude_(arena, from.longitude_),
        latitude_(arena, from.latitude_),
        _cached_size_{0} {}

tracker::tracker(
    ::google::protobuf::Arena* arena,
    const tracker& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  tracker* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::memcpy(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, speed_),
           reinterpret_cast<const char *>(&from._impl_) +
               offsetof(Impl_, speed_),
           offsetof(Impl_, power_) -
               offsetof(Impl_, speed_) +
               sizeof(Impl_::power_));

  // @@protoc_insertion_point(copy_constructor:tracker)
}
inline PROTOBUF_NDEBUG_INLINE tracker::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : coordinates_(arena),
        id_(arena),
        time_track_(arena),
        name_(arena),
        longitude_(arena),
        latitude_(arena),
        _cached_size_{0} {}

inline void tracker::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, speed_),
           0,
           offsetof(Impl_, power_) -
               offsetof(Impl_, speed_) +
               sizeof(Impl_::power_));
}
tracker::~tracker() {
  // @@protoc_insertion_point(destructor:tracker)
  SharedDtor(*this);
}
inline void tracker::SharedDtor(MessageLite& self) {
  tracker& this_ = static_cast<tracker&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.coordinates_.Destroy();
  this_._impl_.id_.Destroy();
  this_._impl_.time_track_.Destroy();
  this_._impl_.name_.Destroy();
  this_._impl_.longitude_.Destroy();
  this_._impl_.latitude_.Destroy();
  this_._impl_.~Impl_();
}

inline void* tracker::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) tracker(arena);
}
constexpr auto tracker::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(tracker),
                                            alignof(tracker));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull tracker::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_tracker_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &tracker::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<tracker>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &tracker::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<tracker>(), &tracker::ByteSizeLong,
            &tracker::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(tracker, _impl_._cached_size_),
        false,
    },
    &tracker::kDescriptorMethods,
    &descriptor_table_tracker_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* tracker::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<4, 9, 0, 68, 2> tracker::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    10, 120,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294966280,  // skipmap
    offsetof(decltype(_table_), field_entries),
    9,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::tracker>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // int32 speed = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(tracker, _impl_.speed_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(tracker, _impl_.speed_)}},
    // int32 battery = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(tracker, _impl_.battery_), 63>(),
     {16, 63, 0, PROTOBUF_FIELD_OFFSET(tracker, _impl_.battery_)}},
    // string coordinates = 3;
    {::_pbi::TcParser::FastUS1,
     {26, 63, 0, PROTOBUF_FIELD_OFFSET(tracker, _impl_.coordinates_)}},
    {::_pbi::TcParser::MiniParse, {}},
    // bool power = 5;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(tracker, _impl_.power_), 63>(),
     {40, 63, 0, PROTOBUF_FIELD_OFFSET(tracker, _impl_.power_)}},
    // string id = 6;
    {::_pbi::TcParser::FastUS1,
     {50, 63, 0, PROTOBUF_FIELD_OFFSET(tracker, _impl_.id_)}},
    // string time_track = 7;
    {::_pbi::TcParser::FastUS1,
     {58, 63, 0, PROTOBUF_FIELD_OFFSET(tracker, _impl_.time_track_)}},
    // string name = 8;
    {::_pbi::TcParser::FastUS1,
     {66, 63, 0, PROTOBUF_FIELD_OFFSET(tracker, _impl_.name_)}},
    // string longitude = 9;
    {::_pbi::TcParser::FastUS1,
     {74, 63, 0, PROTOBUF_FIELD_OFFSET(tracker, _impl_.longitude_)}},
    // string latitude = 10;
    {::_pbi::TcParser::FastUS1,
     {82, 63, 0, PROTOBUF_FIELD_OFFSET(tracker, _impl_.latitude_)}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, {{
    // int32 speed = 1;
    {PROTOBUF_FIELD_OFFSET(tracker, _impl_.speed_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
    // int32 battery = 2;
    {PROTOBUF_FIELD_OFFSET(tracker, _impl_.battery_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
    // string coordinates = 3;
    {PROTOBUF_FIELD_OFFSET(tracker, _impl_.coordinates_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // bool power = 5;
    {PROTOBUF_FIELD_OFFSET(tracker, _impl_.power_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBool)},
    // string id = 6;
    {PROTOBUF_FIELD_OFFSET(tracker, _impl_.id_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string time_track = 7;
    {PROTOBUF_FIELD_OFFSET(tracker, _impl_.time_track_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string name = 8;
    {PROTOBUF_FIELD_OFFSET(tracker, _impl_.name_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string longitude = 9;
    {PROTOBUF_FIELD_OFFSET(tracker, _impl_.longitude_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string latitude = 10;
    {PROTOBUF_FIELD_OFFSET(tracker, _impl_.latitude_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\7\0\0\13\0\2\12\4\11\10\0\0\0\0\0\0"
    "tracker"
    "coordinates"
    "id"
    "time_track"
    "name"
    "longitude"
    "latitude"
  }},
};

PROTOBUF_NOINLINE void tracker::Clear() {
// @@protoc_insertion_point(message_clear_start:tracker)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.coordinates_.ClearToEmpty();
  _impl_.id_.ClearToEmpty();
  _impl_.time_track_.ClearToEmpty();
  _impl_.name_.ClearToEmpty();
  _impl_.longitude_.ClearToEmpty();
  _impl_.latitude_.ClearToEmpty();
  ::memset(&_impl_.speed_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.power_) -
      reinterpret_cast<char*>(&_impl_.speed_)) + sizeof(_impl_.power_));
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* tracker::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const tracker& this_ = static_cast<const tracker&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* tracker::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const tracker& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:tracker)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // int32 speed = 1;
          if (this_._internal_speed() != 0) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt32ToArrayWithField<1>(
                    stream, this_._internal_speed(), target);
          }

          // int32 battery = 2;
          if (this_._internal_battery() != 0) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt32ToArrayWithField<2>(
                    stream, this_._internal_battery(), target);
          }

          // string coordinates = 3;
          if (!this_._internal_coordinates().empty()) {
            const std::string& _s = this_._internal_coordinates();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "tracker.coordinates");
            target = stream->WriteStringMaybeAliased(3, _s, target);
          }

          // bool power = 5;
          if (this_._internal_power() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteBoolToArray(
                5, this_._internal_power(), target);
          }

          // string id = 6;
          if (!this_._internal_id().empty()) {
            const std::string& _s = this_._internal_id();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "tracker.id");
            target = stream->WriteStringMaybeAliased(6, _s, target);
          }

          // string time_track = 7;
          if (!this_._internal_time_track().empty()) {
            const std::string& _s = this_._internal_time_track();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "tracker.time_track");
            target = stream->WriteStringMaybeAliased(7, _s, target);
          }

          // string name = 8;
          if (!this_._internal_name().empty()) {
            const std::string& _s = this_._internal_name();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "tracker.name");
            target = stream->WriteStringMaybeAliased(8, _s, target);
          }

          // string longitude = 9;
          if (!this_._internal_longitude().empty()) {
            const std::string& _s = this_._internal_longitude();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "tracker.longitude");
            target = stream->WriteStringMaybeAliased(9, _s, target);
          }

          // string latitude = 10;
          if (!this_._internal_latitude().empty()) {
            const std::string& _s = this_._internal_latitude();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "tracker.latitude");
            target = stream->WriteStringMaybeAliased(10, _s, target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:tracker)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t tracker::ByteSizeLong(const MessageLite& base) {
          const tracker& this_ = static_cast<const tracker&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t tracker::ByteSizeLong() const {
          const tracker& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:tracker)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // string coordinates = 3;
            if (!this_._internal_coordinates().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_coordinates());
            }
            // string id = 6;
            if (!this_._internal_id().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_id());
            }
            // string time_track = 7;
            if (!this_._internal_time_track().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_time_track());
            }
            // string name = 8;
            if (!this_._internal_name().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_name());
            }
            // string longitude = 9;
            if (!this_._internal_longitude().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_longitude());
            }
            // string latitude = 10;
            if (!this_._internal_latitude().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_latitude());
            }
            // int32 speed = 1;
            if (this_._internal_speed() != 0) {
              total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
                  this_._internal_speed());
            }
            // int32 battery = 2;
            if (this_._internal_battery() != 0) {
              total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
                  this_._internal_battery());
            }
            // bool power = 5;
            if (this_._internal_power() != 0) {
              total_size += 2;
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void tracker::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<tracker*>(&to_msg);
  auto& from = static_cast<const tracker&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:tracker)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_coordinates().empty()) {
    _this->_internal_set_coordinates(from._internal_coordinates());
  }
  if (!from._internal_id().empty()) {
    _this->_internal_set_id(from._internal_id());
  }
  if (!from._internal_time_track().empty()) {
    _this->_internal_set_time_track(from._internal_time_track());
  }
  if (!from._internal_name().empty()) {
    _this->_internal_set_name(from._internal_name());
  }
  if (!from._internal_longitude().empty()) {
    _this->_internal_set_longitude(from._internal_longitude());
  }
  if (!from._internal_latitude().empty()) {
    _this->_internal_set_latitude(from._internal_latitude());
  }
  if (from._internal_speed() != 0) {
    _this->_impl_.speed_ = from._impl_.speed_;
  }
  if (from._internal_battery() != 0) {
    _this->_impl_.battery_ = from._impl_.battery_;
  }
  if (from._internal_power() != 0) {
    _this->_impl_.power_ = from._impl_.power_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void tracker::CopyFrom(const tracker& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:tracker)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void tracker::InternalSwap(tracker* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.coordinates_, &other->_impl_.coordinates_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.id_, &other->_impl_.id_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.time_track_, &other->_impl_.time_track_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.name_, &other->_impl_.name_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.longitude_, &other->_impl_.longitude_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.latitude_, &other->_impl_.latitude_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(tracker, _impl_.power_)
      + sizeof(tracker::_impl_.power_)
      - PROTOBUF_FIELD_OFFSET(tracker, _impl_.speed_)>(
          reinterpret_cast<char*>(&_impl_.speed_),
          reinterpret_cast<char*>(&other->_impl_.speed_));
}

::google::protobuf::Metadata tracker::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class tracker_list::_Internal {
 public:
};

tracker_list::tracker_list(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:tracker_list)
}
inline PROTOBUF_NDEBUG_INLINE tracker_list::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::tracker_list& from_msg)
      : trackers_{visibility, arena, from.trackers_},
        _cached_size_{0} {}

tracker_list::tracker_list(
    ::google::protobuf::Arena* arena,
    const tracker_list& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  tracker_list* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:tracker_list)
}
inline PROTOBUF_NDEBUG_INLINE tracker_list::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : trackers_{visibility, arena},
        _cached_size_{0} {}

inline void tracker_list::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
tracker_list::~tracker_list() {
  // @@protoc_insertion_point(destructor:tracker_list)
  SharedDtor(*this);
}
inline void tracker_list::SharedDtor(MessageLite& self) {
  tracker_list& this_ = static_cast<tracker_list&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* tracker_list::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) tracker_list(arena);
}
constexpr auto tracker_list::InternalNewImpl_() {
  constexpr auto arena_bits = ::google::protobuf::internal::EncodePlacementArenaOffsets({
      PROTOBUF_FIELD_OFFSET(tracker_list, _impl_.trackers_) +
          decltype(tracker_list::_impl_.trackers_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
  });
  if (arena_bits.has_value()) {
    return ::google::protobuf::internal::MessageCreator::ZeroInit(
        sizeof(tracker_list), alignof(tracker_list), *arena_bits);
  } else {
    return ::google::protobuf::internal::MessageCreator(&tracker_list::PlacementNew_,
                                 sizeof(tracker_list),
                                 alignof(tracker_list));
  }
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull tracker_list::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_tracker_list_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &tracker_list::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<tracker_list>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &tracker_list::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<tracker_list>(), &tracker_list::ByteSizeLong,
            &tracker_list::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(tracker_list, _impl_._cached_size_),
        false,
    },
    &tracker_list::kDescriptorMethods,
    &descriptor_table_tracker_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* tracker_list::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 1, 0, 2> tracker_list::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::tracker_list>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // repeated .tracker trackers = 1;
    {::_pbi::TcParser::FastMtR1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(tracker_list, _impl_.trackers_)}},
  }}, {{
    65535, 65535
  }}, {{
    // repeated .tracker trackers = 1;
    {PROTOBUF_FIELD_OFFSET(tracker_list, _impl_.trackers_), 0, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kMessage | ::_fl::kTvTable)},
  }}, {{
    {::_pbi::TcParser::GetTable<::tracker>()},
  }}, {{
  }},
};

PROTOBUF_NOINLINE void tracker_list::Clear() {
// @@protoc_insertion_point(message_clear_start:tracker_list)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.trackers_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* tracker_list::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const tracker_list& this_ = static_cast<const tracker_list&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* tracker_list::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const tracker_list& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:tracker_list)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // repeated .tracker trackers = 1;
          for (unsigned i = 0, n = static_cast<unsigned>(
                                   this_._internal_trackers_size());
               i < n; i++) {
            const auto& repfield = this_._internal_trackers().Get(i);
            target =
                ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
                    1, repfield, repfield.GetCachedSize(),
                    target, stream);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:tracker_list)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t tracker_list::ByteSizeLong(const MessageLite& base) {
          const tracker_list& this_ = static_cast<const tracker_list&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t tracker_list::ByteSizeLong() const {
          const tracker_list& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:tracker_list)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // repeated .tracker trackers = 1;
            {
              total_size += 1UL * this_._internal_trackers_size();
              for (const auto& msg : this_._internal_trackers()) {
                total_size += ::google::protobuf::internal::WireFormatLite::MessageSize(msg);
              }
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void tracker_list::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<tracker_list*>(&to_msg);
  auto& from = static_cast<const tracker_list&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:tracker_list)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_trackers()->MergeFrom(
      from._internal_trackers());
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void tracker_list::CopyFrom(const tracker_list& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:tracker_list)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void tracker_list::InternalSwap(tracker_list* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.trackers_.InternalSwap(&other->_impl_.trackers_);
}

::google::protobuf::Metadata tracker_list::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_tracker_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
